[build]
  publish = "frontend/build"
  command = "cd frontend && rm -f package-lock.json && yarn install --frozen-lockfile && yarn build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  NPM_VERSION = "10"
  CI = "true"

[[redirects]]
  from = "/api/*"
  to = "https://e239b078-6e78-47a7-b7f1-cef6da6b3bb4.e1-us-east-1.amy.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"